Repository quarkiverse/quarkus-quinoa, pull requests merged in 2023-12, with the labels that each got.

#572 NextJS 14 `next export` has been removed
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
  docs/modules/ROOT/pages/web-frameworks.adoc
Labels: enhancement

#594 Fix dev service restart condition
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/FrameworkConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerCommandConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
Labels: bug, backport-2.2.x

#593 Smart bypass of the dev server SPA
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/DevServerConfigDelegate.java
  docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
  integration-tests/src/main/resources/application.properties
  integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaRootPathTest.java
  integration-tests/src/test/java/io/quarkiverse/quinoa/it/TestProfiles.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaHandlerConfig.java
Labels: backport-2.2.x

#596 2.2.x backports for LTS
  pom.xml
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
Labels: backport-2.2.x
