Repository quarkiverse/quarkus-quinoa, pull requests merged in 2023-08, with the labels that each got.

#458 include `scm` in connection
  pom.xml
Labels: enhancement

#457 Bump lit to v2.8.0
  integration-tests/src/main/ui-lit/package-lock.json
  integration-tests/src/main/ui-lit/package.json
Labels: enhancement

#465 Added .gitattributes to repo
  .gitattributes
Labels: feature

#472 Update Quinoa 2.0.8
  docs/modules/ROOT/pages/includes/attributes.adoc
Labels: documentation

#477 Refine Support
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
Labels: feature

#478 document refine
  docs/modules/ROOT/pages/index.adoc
Labels: documentation

#479 devolup -> develope
  deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallPrependBinaryTest.java
  deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNPMOverrideBuildEnvTest.java
  deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNPMOverrideEnvTest.java
Labels: enhancement

#480 fix: Dependabot vulnerabilities alerts
  integration-tests/src/main/ui-angular/package-lock.json
  integration-tests/src/main/ui-vue/yarn.lock
Labels: dependencies

#484 Fix #481: URLEncode UI resources
  docs/modules/ROOT/pages/includes/attributes.adoc
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java
Labels: bug

#487 remove wrapper in log
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java
Labels: enhancement

#490 Update README.md - add a link to repository map
  README.md
Labels: documentation
