Repository quarkiverse/quarkus-quinoa, pull requests merged in 2024-01, with the labels that each got.

#605 Better error for missing static index page
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java
Labels: enhancement

#607 [Critical] Make sure the devServer indexPage is only used in dev mode
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaHandlerConfig.java
  runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java
Labels: backport-2.2.x

#615 Create new config for authentication in VertxFileDownloader
  deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/PackageManagerInstallFactory.java
  deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallAuthConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
  docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
Labels: enhancement, backport-2.2.x

#616 2.2.x Create new config for authentication in VertxFileDownloader
  deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/PackageManagerInstallFactory.java
  deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallAuthConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
  deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
  docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
Labels: backport-2.2.x
